// Run with NODE_PATH pointing to an installation of Playwright.
const { chromium } = require('playwright');
const fs = require('node:fs');
const path = require('node:path');
const assert = require('node:assert/strict');
(async () => {
  const out = path.resolve('qa-output', process.argv[2] || 'current');
  fs.mkdirSync(out, { recursive: true });
  const browser = await chromium.launch({ channel: 'chrome', headless: true });
  const context = await browser.newContext({ timezoneId: 'Asia/Shanghai', serviceWorkers: 'block' });
  await context.route('**/*', route => new URL(route.request().url()).hostname === '127.0.0.1' ? route.continue() : route.abort());
  const page = await context.newPage();
  const errors = [], results = [];
  page.on('pageerror', e => errors.push(e.message));
  for (const width of [1440, 1280, 900, 768, 390, 320]) {
    await page.setViewportSize({ width, height: 900 });
    await page.goto('http://127.0.0.1:18787');
    await page.waitForFunction(() => document.querySelector('#holdingList .fund-row'));
    for (const id of ['dashboard', 'holdings', 'health', 'manage', 'sync', 'market']) {
      await page.evaluate(id => go(id), id);
      if (!await page.locator('#' + id).count()) continue;
      const layout = await page.evaluate(() => ({
        viewport: innerWidth, scrollWidth: document.documentElement.scrollWidth,
        overflow: [...document.querySelectorAll('.page.active *')].filter(e => {
          const r = e.getBoundingClientRect(); return r.width > 0 && r.right > innerWidth + 2;
        }).slice(0, 8).map(e => e.id || e.className)
      }));
      results.push({ width, page: id, ...layout });
      if (id === 'dashboard' && width <= 600) {
        const cards = await page.locator('.personal-kpis article').evaluateAll(elements => elements.map(e => e.getBoundingClientRect().top));
        assert(cards[2] > cards[0], `Dashboard KPI cards are hidden in a horizontal strip at ${width}px`);
      }
      if (id === 'dashboard') assert.equal(await page.locator('#profitRateValue').innerText(), '+2.88%');
      await page.screenshot({ path: path.join(out, `${id}-${width}.png`), fullPage: true });
    }
  }
  await page.setViewportSize({width: 390, height: 740});
  await page.goto('http://127.0.0.1:18787');
  await page.waitForFunction(() => document.querySelector('#holdingList .fund-row'));
  assert.equal(await page.locator('#research, [data-page="research"], [data-module="research"]').count(), 0);
  await page.locator('.kpi-link').click();
  assert(await page.locator('#holdings').evaluate(element => element.classList.contains('active')));
  await page.waitForFunction(() => document.querySelector('#holdingCalendarRows').textContent.includes('排版测试 ETF'));
  assert(await page.locator('#holdingCalendarRows').innerText().then(text => text.includes('已清仓')));
  await page.locator('#holdingPrev').click();
  await page.waitForFunction(() => document.querySelector('#holdingCalendarRows').textContent.includes('已清仓于 2026-10-01'));
  await page.locator('#holdingPrev').click();
  await page.waitForFunction(() => document.querySelector('#holdingCalendarRows').textContent.includes('¥1,200.00'));
  assert(await page.locator('#holdingCalendarRows .calendar-row').filter({hasText:'排版测试 ETF'}).innerText().then(text => text.includes('持有收益率 +20.00%')));
  assert(await page.locator('#holdingCalendarRows .calendar-row').filter({hasText:'排版测试 ETF'}).innerText().then(text => text.includes('持有收益 +¥200.00')));
  await page.locator('.calendar-positions').screenshot({path:path.join(out,'september-etf-390.png')});
  await page.locator('#holdingPrev').click();
  await page.waitForFunction(() => document.querySelector('#holdingCalendarRows').textContent.includes('¥1,000.00'));
  assert(await page.locator('#holdingCalendarRows .calendar-row').filter({hasText:'排版测试 ETF'}).innerText().then(text => text.includes('持有收益率 +0.00%')));
  await page.locator('#holdingToday').click();
  await page.waitForFunction(() => document.querySelector('#holdingForm [name="day"]').value === localDay());
  await page.locator('#holdingForm [name="category"]').selectOption('ETF');
  await page.locator('#holdingForm [name="code"]').fill('588000');
  await page.locator('#holdingForm [name="name"]').fill('浏览器回归 ETF');
  await page.locator('#holdingForm [name="market_value"]').fill('200');
  await page.locator('#holdingForm [name="holding_profit"]').fill('0');
  await page.locator('#holdingForm [name="return_rate"]').fill('0');
  await page.locator('#holdingForm [name="day"]').fill('2026-10-05');
  await page.locator('#holdingForm button.primary').click();
  await page.waitForFunction(() => document.querySelector('#holdingCalendarRows').textContent.includes('浏览器回归 ETF'));
  await page.locator('#holdingForm [name="day"]').fill('2026-10-07');
  await page.locator('#holdingClear').click();
  await page.waitForFunction(() => document.querySelector('#holdingCalendarRows').textContent.includes('浏览器回归 ETF') && document.querySelector('#holdingCalendarRows').textContent.includes('已清仓于 2026-10-07'));
  assert(!(await page.request.get('http://127.0.0.1:18787/api/state').then(r=>r.json())).holdings.some(h => h.code === '588000'));
  await page.evaluate(() => go('dashboard'));
  assert.equal(await page.locator('#profitRateValue').innerText(), '+2.88%');
  await page.locator('#userMenuButton').click();
  await page.locator('#userMenu [data-page="manage"]').click();
  await page.locator('#activeHoldingActions [data-action="history"]').first().click();
  await page.waitForFunction(() => document.querySelector('#holdingHistory .history-title'));
  assert(await page.locator('#holdingHistory').isVisible());
  await page.evaluate(() => go('holdings'));
  assert.equal(await page.locator('#holdingList2 .planned-investment, #todayPlanTotal').count(), 0);
  await page.locator('#allocationTargetRows [data-strategy-code]').first().click();
  await page.locator('#strategyForm select[name="mode"]').selectOption('drawdown');
  const panel = await page.locator('.strategy-panel').boundingBox();
  assert(panel.x >= 0 && panel.y >= 0 && panel.x + panel.width <= 391 && panel.y + panel.height <= 741);
  await page.locator('#strategyForm [name="drawdown_budget"]').fill('1000');
  await page.locator('#strategyForm button.primary').click();
  await page.waitForFunction(() => document.querySelector('.strategy-panel').hidden);
  assert.equal((await page.request.get('http://127.0.0.1:18787/api/state').then(r=>r.json())).holdings[0].investment_strategy.mode, 'drawdown');
  await page.locator('#allocationPlanForm [name="monthly_budget"]').fill('100');
  await page.locator('#allocationPlanForm [data-target-key="000001"]').fill('0');
  await page.locator('#allocationPlanForm [data-target-key="000002"]').fill('50');
  await page.locator('#allocationPlanForm [data-target-key="000003"]').fill('50');
  await page.locator('#allocationPlanForm button[type="submit"]').click();
  await page.waitForFunction(() => state.allocationPlan?.ready);
  const unified = (await page.request.get('http://127.0.0.1:18787/api/state').then(r=>r.json())).allocationPlan;
  assert.equal(unified.allocated, '100.00');
  assert.equal(unified.rows.find(row => row.code === '000001').buy_amount, '0.00');
  assert.equal(await page.locator('#allocationPlanSummary .allocation-order').count(), 1);
  assert(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 2));
  await page.locator('#allocationPlanForm').screenshot({path:path.join(out,'unified-plan-390.png')});
  await page.evaluate(() => {
    state={holdings:[], accounts:[{name:'零余额',account_type:'现金',balance:'0'}], total:'0',fundTotal:'0',totalCost:'0',profit:'0',snapshots:[]};
    renderDashboard();renderAllocation();renderAdvice();go('dashboard');
  });
  assert(!/NaN|Infinity/.test(await page.locator('#dashboard').innerText()));
  assert.equal(await page.locator('#profitRateValue').innerText(), '—');
  assert.equal(await page.locator('#riskLevel').innerText(), '—');
  const local = await page.evaluate(() => localDay(new Date('2026-09-07T01:00:00+08:00')));
  assert.equal(local, '2026-09-07');
  await page.screenshot({path:path.join(out,'empty-dashboard-390.png'),fullPage:true});
  await page.goto('http://127.0.0.1:18787');
  await page.waitForFunction(() => document.querySelector('#holdingList .fund-row'));
  await page.evaluate(() => go('holdings'));
  await page.locator('#accountForm [name="name"]').fill('浏览器回归账户');
  await page.locator('#accountForm [name="platform"]').fill('测试平台');
  await page.locator('#accountForm [name="balance"]').fill('123.45');
  await page.locator('#accountForm button').click();
  await page.waitForFunction(() => document.querySelector('#accountList').textContent.includes('浏览器回归账户'));
  await page.locator('#holdingForm [name="name"]').fill('浏览器回归基金');
  await page.locator('#holdingForm [name="market_value"]').fill('105');
  await page.locator('#holdingForm [name="holding_profit"]').fill('5');
  await page.locator('#holdingForm [name="return_rate"]').fill('4.76');
  await page.locator('#holdingForm button.primary').click();
  await page.waitForFunction(() => document.querySelector('#holdingList2').textContent.includes('浏览器回归基金'));
  await page.evaluate(() => go('dashboard'));
  assert(!await page.locator('#returnQuality').innerText().then(text => text.includes('%')));
  await page.evaluate(() => go('health'));
  await page.locator('#healthForm [name="steps"]').fill('8000');
  await page.locator('#healthForm [name="sleep_minutes"]').fill('480');
  await page.locator('#healthForm button').click();
  await page.waitForFunction(() => document.querySelector('#stepsKpi').textContent.includes('8,000'));
  await page.evaluate(() => go('manage'));
  const archivedBefore = await page.locator('#archivedHoldingList .archived').count();
  page.once('dialog', dialog => dialog.accept());
  await page.locator('#activeHoldingActions [data-action="archive"]').first().click();
  await page.waitForFunction(n => document.querySelectorAll('#archivedHoldingList .archived').length === n + 1, archivedBefore);
  await page.locator('#archivedHoldingList .archived button').filter({hasText:'恢复'}).first().click();
  await page.waitForFunction(n => document.querySelectorAll('#archivedHoldingList .archived').length === n, archivedBefore);
  const saved = await page.request.get('http://127.0.0.1:18787/api/state').then(r => r.json());
  assert(saved.accounts.some(a => a.name === '浏览器回归账户' && a.balance === '123.45'));
  assert(saved.holdings.some(h => h.name === '浏览器回归基金' && h.cost === '0.00'));
  assert.equal(saved.totalCost, null);
  assert.equal(saved.holdings.length, 4);
  await browser.close();
  fs.writeFileSync(path.join(out, 'layout.json'), JSON.stringify({ errors, results }, null, 2));
  console.log(JSON.stringify({ errors, overflows: results.filter(r => r.scrollWidth > r.viewport + 2), checks: results.length }, null, 2));
  assert.equal(errors.length, 0, 'Uncaught browser errors');
  assert.equal(results.filter(r => r.scrollWidth > r.viewport + 2).length, 0, 'Page overflow');
})().catch(e => { console.error(e); process.exitCode = 1; });
